//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMangment.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelMangmentEntities : DbContext
    {
        public HotelMangmentEntities()
            : base("name=HotelMangmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLcustomer> TBLcustomers { get; set; }
        public virtual DbSet<TBLreservation> TBLreservations { get; set; }
        public virtual DbSet<TBLroomReservation> TBLroomReservations { get; set; }
        public virtual DbSet<TBLroom> TBLrooms { get; set; }
    }
}
