//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMangment.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLroomReservation
    {
        public int id { get; set; }
        public Nullable<int> roomID { get; set; }
        public Nullable<int> reservationID { get; set; }
    
        public virtual TBLreservation TBLreservation { get; set; }
        public virtual TBLroom TBLroom { get; set; }
    }
}
